### ISSUE TITLE
ssr订阅报错

### ISSUE THREAD

**Issue by zheshifandian** [fw876/helloworld#373] opened 2021-02-08 23:55 UTC
2021-02-09 07:44:14 重启服务成功
2021-02-09 07:44:14 发生错误, 正在恢复服务
	[C]: ?
	/usr/share/shadowsocksr/subscribe.lua:512: in main chunk
	[C]: in function 'xpcall'
	/usr/share/shadowsocksr/subscribe.lua:413: in function </usr/share/shadowsocksr/subscribe.lua:365>
	/usr/share/shadowsocksr/subscribe.lua:126: in function 'processData'
	/usr/share/shadowsocksr/subscribe.lua:514: in function </usr/share/shadowsocksr/subscribe.lua:512>
2021-02-09 07:44:14 stack traceback:
2021-02-09 07:44:14 /usr/share/shadowsocksr/subscribe.lua:126: attempt to index local 'info' (a nil value)
2021-02-09 07:44:12 成功解析节点数量: 43

**Comment by 1715173329** [comment] 2021-02-09 13:20
This is a duplicate of immortalwrt/immortalwrt#280.

**Closed** 2021-02-12 01:32 UTC
